image: node:7

before_script:
  - npm install

build:
  script:
    - npm run build

test:
  script:
    - npm run test

pages:
  stage: deploy
  script:
  - cd public-site && npm install && ./node_modules/.bin/hexo generate
  artifacts:
    paths:
    - public-site/public
  only:
  - master
