image: node:7

before_script:
  - npm install

build:
  script:
    - npm run build

test:
  script:
    - npm run test

integration-test:
  services:
    - postgres

  variables:
    POSTGRES_HOST: postgres
    POSTGRES_USER: prism-integration-test-user
    POSTGRES_PASSWORD: prism-integration-test-password

  script:
    - apt-get update -y
    - apt-get install postgresql-client -y
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - npm run build
    - cd integration-test/postgresql
    - ./run.sh

pages:
  stage: deploy
  script:
  - cd public-site
  - npm install
  - ./node_modules/.bin/hexo generate
  - mv ./public ../
  artifacts:
    paths:
    - public
  only:
  - master
