dist: trusty
language: node_js
sudo: false

cache:
  directories:
    - node_modules

env:
  - POSTGRES_USER=postgres

node_js:
  - '6'

services:
  - postgresql

before_install:
  npm install -g npm

install:
  - npm install

script:
  - npm run test
  - npm run build
  - cd integration-test/postgresql
  - ./run.sh
