dist: trusty
language: node_js
sudo: false

cache:
  directories:
    - node_modules
    - integration-test/postgresql/node_modules

env:
  - POSTGRES_USER=postgres

node_js:
  - '6'

services:
  - postgresql

install:
  - npm install

script:
  - npm run test
  - npm run build
  - cd integration-test/postgresql
  - npm install
  - ./run.sh
